# Generated by Django 4.2.4 on 2023-08-27 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='letter',
            name='submitted',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
